export type {
  CityRow,
  CountryRow,
  CreateCityPayload,
  CreateCountryPayload,
  CreateHandoverLocationPayload,
  CreateReservationExtraOptionTemplatePayload,
  CreateVehicleOptionTemplatePayload,
  CreateVehiclePayload,
  HandoverLocationApiRow,
  ReservationExtraOptionTemplateApiRow,
  UpdateHandoverLocationPayload,
  UpdateReservationExtraOptionTemplatePayload,
  UpdateVehicleOptionTemplatePayload,
  UpdateVehiclePayload,
  VehicleBodyStyleRow,
  VehicleCatalogCreatePayload,
  VehicleCatalogRow,
  VehicleCatalogUpdatePayload,
  VehicleFormCatalog,
  VehicleFormCatalogBrandRow,
  VehicleFormCatalogModelRow,
  VehicleFormCatalogVehicleStatusRow,
  VehicleOptionDefinitionPayload,
  VehicleOptionTemplateApiRow,
} from "@/models/vehicle";
export type {
  CreateRentalPayload,
  FetchRentalDashboardParams,
  FetchRentalsParams,
  RentalDashboardReport,
  RentalDashboardSummary,
  RentalDashboardTimelineRow,
  RentalDashboardVehicleRow,
  RentalRequestDto,
  RentalRequestFormPayload,
  RentalRequestStatus,
  UpdateRentalPayload,
} from "@/models/rental";
export type { CustomerRecordDeletionPayload, CustomerRecordStatePayload } from "@/models/customer";
